[package]
name = "bounty-escrow"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = "21.0.0"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["alloc", "testutils"] }
proptest = "1.0"
